package com.myspace.shaelectric;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Advertisement implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Advertisement() {
    }




}