package com.myspace.shaelectric;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Advertisement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String channel;
	private java.lang.String type;
	private java.lang.Double price;

	private java.lang.Boolean proposalAccepted;

	private java.lang.Boolean finalAccepted;

	public Advertisement() {
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.Boolean getProposalAccepted() {
		return this.proposalAccepted;
	}

	public void setProposalAccepted(java.lang.Boolean proposalAccepted) {
		this.proposalAccepted = proposalAccepted;
	}

	public java.lang.Boolean getFinalAccepted() {
		return this.finalAccepted;
	}

	public void setFinalAccepted(java.lang.Boolean finalAccepted) {
		this.finalAccepted = finalAccepted;
	}

	public Advertisement(java.lang.String channel, java.lang.String type,
			java.lang.Double price, java.lang.Boolean proposalAccepted,
			java.lang.Boolean finalAccepted) {
		this.channel = channel;
		this.type = type;
		this.price = price;
		this.proposalAccepted = proposalAccepted;
		this.finalAccepted = finalAccepted;
	}

}