package com.myspace.shaelectric;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LEV implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LEV() {
    }




}