package com.myspace.shaelectric;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UserDb implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String surname;

	private java.lang.String email;

	private java.lang.String password;

	public UserDb() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public UserDb(java.lang.String name, java.lang.String surname,
			java.lang.String email, java.lang.String password) {
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.password = password;
	}

}